# Generated by Django 5.0.7 on 2024-07-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todod',
            new_name='Todo',
        ),
    ]
